# Copy this file to .streamlit/secrets.toml and set your credentials.
# Do not commit .streamlit/secrets.toml with real secrets.

gemini_api_key = "YOUR_GEMINI_API_KEY"

# --- Optional Basic Authentication ---
# Provide either a plain password or a precomputed SHA-256 hash.
# When both are set, the hash takes precedence.
#
# basic_auth_username = "your-username"
# basic_auth_password = "your-password"
# basic_auth_password_hash = "your-password-sha256-hex"
